var ageingTrend = {
	2010: [
		{"name":"辽宁省","value":15.4},
		{"name": "黑龙江省", "value": 13},
		{"name": "吉林省", "value": 13.2},
		{"name": "天津市", "value": 13},
		{"name": "上海市", "value": 15.1},
		{"name": "内蒙古自治区", "value": 11.5},
		{"name": "山西省", "value": 11.5},
		{"name": "北京市", "value": 12.5},
		{"name": "河北省", "value": 13},
		{"name": "湖北省", "value": 13.9},
		{"name": "陕西省", "value": 12.9},
		{"name": "山东省", "value": 14.8},
		{"name": "江苏省", "value": 16},
		{"name": "江西省", "value": 11.4},
		{"name": "四川省", "value": 16.3},
		{"name": "河南省", "value": 12.7},
		{"name": "湖南省", "value": 14.5},
		{"name": "浙江省", "value": 13.9},
		{"name": "甘肃省", "value": 12.4},
		{"name": "福建省", "value": 11.4},
		{"name": "重庆市", "value": 17.4},
		{"name": "宁夏回族自治区", "value": 9.7},
		{"name": "云南省", "value": 11.1},
		{"name": "安徽省", "value": 15},
		{"name": "广西壮族自治区", "value": 13.1},
		{"name": "海南省", "value": 11.3},
		{"name": "青海省", "value": 9.5},
		{"name": "广东省", "value": 9.7},
		{"name": "贵州省", "value": 12.8},
		{"name": "新疆维吾尔自治区", "value": 9.7},
		{"name": "西藏自治区", "value": 7.7}
	],
	2020: [
		{"name": "辽宁省", "value": 25.7},
		{"name": "黑龙江省", "value": 23.2},
		{"name": "吉林省", "value": 23.1},
		{"name": "天津市", "value": 21.7},
		{"name": "上海市", "value": 23.4},
		{"name": "内蒙古自治区", "value": 19.8},
		{"name": "山西省", "value": 18.9},
		{"name": "北京市", "value": 19.6},
		{"name": "河北省", "value": 19.9},
		{"name": "湖北省", "value": 20.4},
		{"name": "陕西省", "value": 19.2},
		{"name": "山东省", "value": 20.9},
		{"name": "江苏省", "value": 21.8},
		{"name": "江西省", "value": 16.9},
		{"name": "四川省", "value": 21.7},
		{"name": "河南省", "value": 18.1},
		{"name": "湖南省", "value": 19.9},
		{"name": "浙江省", "value": 18.7},
		{"name": "甘肃省", "value": 17},
		{"name": "福建省", "value": 16}, 
		{"name": "重庆市", "value": 21.9},
		{"name": "宁夏回族自治区", "value": 13.5},
		{"name": "云南省", "value": 14.9},
		{"name": "安徽省", "value": 18.8},
		{"name": "广西壮族自治区", "value": 16.7},
		{"name": "海南省", "value": 14.7},
		{"name": "青海省", "value": 12.2},
		{"name": "广东省", "value": 12.4},
		{"name": "贵州省", "value": 15.4},
		{"name": "新疆维吾尔自治区", "value": 11.3},
		{"name": "西藏自治区", "value": 8.5}
	]
};
var ageingData = {
	"中华人民共和国": [
		{"name": "辽宁省", "value": 25.7},
		{"name": "黑龙江省", "value": 23.2},
		{"name": "吉林省", "value": 23.1},
		{"name": "天津市", "value": 21.7},
		{"name": "上海市", "value": 23.4},
		{"name": "内蒙古自治区", "value": 19.8},
		{"name": "山西省", "value": 18.9},
		{"name": "北京市", "value": 19.6},
		{"name": "河北省", "value": 19.9},
		{"name": "湖北省", "value": 20.4},
		{"name": "陕西省", "value": 19.2},
		{"name": "山东省", "value": 20.9},
		{"name": "江苏省", "value": 21.8},
		{"name": "江西省", "value": 16.9},
		{"name": "四川省", "value": 21.7},
		{"name": "河南省", "value": 18.1},
		{"name": "湖南省", "value": 19.9},
		{"name": "浙江省", "value": 18.7},
		{"name": "甘肃省", "value": 17},
		{"name": "福建省", "value": 16}, 
		{"name": "重庆市", "value": 21.9},
		{"name": "宁夏回族自治区", "value": 13.5},
		{"name": "云南省", "value": 14.9},
		{"name": "安徽省", "value": 18.8},
		{"name": "广西壮族自治区", "value": 16.7},
		{"name": "海南省", "value": 14.7},
		{"name": "青海省", "value": 12.2},
		{"name": "广东省", "value": 12.4},
		{"name": "贵州省", "value": 15.4},
		{"name": "新疆维吾尔自治区", "value": 11.3},
		{"name": "西藏自治区", "value": 8.5}
	],
	"北京市": [
		{"name": "通州区", "value": 30.9},
		{"name": "东城区", "value": 26.4},
		{"name": "西城区", "value": 26},
		{"name": "石景山区", "value": 24.3},
		{"name": "平谷区", "value": 24},
		{"name": "丰台区", "value": 23.7},
		{"name": "密云区", "value": 23.1},
		{"name": "延庆区", "value": 23},
		{"name": "门头沟区", "value": 22.6},
		{"name": "朝阳区", "value": 20.5},
		{"name": "房山区", "value": 19.8},
		{"name": "怀柔区", "value": 19.5},
		{"name": "海淀区", "value": 18.5},
		{"name": "顺义区", "value": 16.5},
		{"name": "大兴区", "value": 15},
		{"name": "昌平区", "value": 14.9},
	],
	"天津市": [
		{"name": "河北区", "value": 31},
		{"name": "红桥区", "value": 30.7},
		{"name": "河东区", "value": 28.8},
		{"name": "南开区", "value": 28.1},
		{"name": "河西区", "value": 28},
		{"name": "蓟州区", "value": 22.8},
		{"name": "宁河区", "value": 22.6},
		{"name": "和平区", "value": 22.1},
		{"name": "宝坻区", "value": 22},
		{"name": "北辰区", "value": 20.5},
		{"name": "武清区", "value": 19.9},
		{"name": "静海区", "value": 18.7},
		{"name": "东丽区", "value": 18.3},
		{"name": "滨海新区", "value": 17.2},
		{"name": "西青区", "value": 16.5},
		{"name": "津南区", "value": 15.9}
	],
	"上海市": [
		{"name": "崇明区", "value": 39.7},
		{"name": "杨浦区", "value": 31.8},
		{"name": "静安区", "value": 31.6},
		{"name": "普陀区", "value": 30.6},
		{"name": "金山区", "value": 23.6},
		{"name": "宝山区", "value": 22.9},
		{"name": "浦东新区", "value": 21.6},
		{"name": "奉贤区", "value": 19.3},
		{"name": "嘉定区", "value": 17.9},
		{"name": "闵行区"},
		{"name": "松江区"},
		{"name": "黄浦区", "value": 8.4},
		{"name": "虹口区", "value": 33.2},
		{"name": "徐汇区", "value": 28.7},
		{"name": "长宁区"},
		{"name": "青浦区"}
	],
	"重庆市": [
		{"name": "合川区", "value": 27.1},
		{"name": "忠县", "value": 26.5},
		{"name": "铜梁区", "value": 26.1},
		{"name": "潼南区", "value": 25.7},
		{"name": "长寿区", "value": 25.4},
		{"name": "綦江区", "value": 25.2},
		{"name": "荣昌区", "value": 25.1},
		{"name": "江津区", "value": 25},
		{"name": "梁平区", "value": 25},
		{"name": "丰都县", "value": 24.6},
		{"name": "垫江县", "value": 24.5},
		{"name": "万州区", "value": 23.9},
		{"name": "南川区", "value": 23.6},
		{"name": "武隆区", "value": 23.6},
		{"name": "云阳县", "value": 23.5},
		{"name": "石柱土家族自治县", "value": 23.2},
		{"name": "巫溪县", "value": 23.2},
		{"name": "开州区", "value": 22.8},
		{"name": "大足区", "value": 22.6},
		{"name": "奉节县", "value": 22.3},
		{"name": "巫山县", "value": 21.9},
		{"name": "巴南区", "value": 21.8},
		{"name": "璧山区", "value": 21.4},
		{"name": "北碚区", "value": 21.2},
		{"name": "涪陵区", "value": 21.2},
		{"name": "永川区", "value": 20.8},
		{"name": "酉阳土家族苗族自治县", "value": 20.6},
		{"name": "城口县", "value": 20.5},
		{"name": "彭水苗族土家族自治县", "value": 20.3},
		{"name": "秀山土家族苗族自治县", "value": 20},
		{"name": "渝中区", "value": 19.8},
		{"name": "大渡口区", "value": 19.6},
		{"name": "江北区", "value": 19.1},
		{"name": "黔江区", "value": 18.5},
		{"name": "九龙坡区", "value": 18.1},
		{"name": "南岸区", "value": 18.1},
		{"name": "沙坪坝区", "value": 16.8},
		{"name": "渝北区", "value": 16.4}
	],
	"河北省": [
		{"name": "石家庄市", "value": 18},
		{"name": "唐山市", "value": 22.8},
		{"name": "秦皇岛市", "value": 23.4},
		{"name": "邯郸市", "value": 17.2},
		{"name": "邢台市", "value": 18.4},
		{"name": "保定市", "value": 19.8},
		{"name": "张家口市", "value": 25.1},
		{"name": "承德市", "value": 22},
		{"name": "廊坊市", "value": 16.9},
		{"name": "沧州市", "value": 19.7},
		{"name": "衡水市", "value": 21.8},
		{"name": "辛集市", "value": 26.1},
		{"name": "定州市", "value": 20.4}
	],
	"山西省": [
		{"name": "太原市", "value": 16.1},
		{"name": "大同市", "value": 20.6},
		{"name": "阳泉市", "value": 20.8},
		{"name": "长治市", "value": 19.2},
		{"name": "晋城市", "value": 20.3},
		{"name": "朔州市", "value": 18.2},
		{"name": "晋中市", "value": 19},
		{"name": "临汾市", "value": 18.1},
		{"name": "运城市", "value": 20},
		{"name": "忻州市", "value": 22.7},
		{"name": "吕梁市", "value": 16.7}
	],
	"内蒙古自治区": [
		{"name": "呼和浩特市", "value": 18},
		{"name": "包头市", "value": 20.2},
		{"name": "乌海市", "value": 16.4},
		{"name": "赤峰市", "value": 21.1},
		{"name": "通辽市", "value": 18.7},
		{"name": "鄂尔多斯市", "value": 15},
		{"name": "呼伦贝尔市", "value": 20.5},
		{"name": "巴彦淖尔市", "value": 21.1},
		{"name": "乌兰察布市", "value": 30},
		{"name": "兴安盟", "value": 18},
		{"name": "锡林郭勒盟", "value": 17.9},
		{"name": "阿拉善盟", "value": 14.4}
	],
	"辽宁省": [
		{"name": "沈阳市", "value": 23.2},
		{"name": "大连市", "value": 24.7},
		{"name": "鞍山市", "value": 27.3},
		{"name": "抚顺市", "value": 27.3},
		{"name": "本溪市", "value": 29},
		{"name": "丹东市", "value": 29},
		{"name": "锦州市", "value": 28.6},
		{"name": "营口市", "value": 25.1},
		{"name": "阜新市", "value": 26.3},
		{"name": "盘锦市", "value": 22.7},
		{"name": "铁岭市", "value": 26.8},
		{"name": "辽阳市", "value": 27.9},
		{"name": "朝阳市", "value": 24.3},
		{"name": "葫芦岛市", "value": 25.6}
	],
	"吉林省": [
		{"name": "长春市", "value": 20.9},
		{"name": "吉林市", "value": 25.3},
		{"name": "四平市", "value": 24.5},
		{"name": "辽源市", "value": 25.4},
		{"name": "通化市", "value": 25.9},
		{"name": "白山市", "value": 25.3},
		{"name": "松原市", "value": 21.5},
		{"name": "白城市", "value": 23.6},
		{"name": "延边朝鲜族自治州", "value": 24.9},
		{"name": "梅河口市", "value": 24.1}
	],
	"黑龙江省": [
		{"name": "哈尔滨市", "value": 22},
		{"name": "齐齐哈尔市", "value": 24.1},
		{"name": "鸡西市", "value": 25.2},
		{"name": "鹤岗市", "value": 24.3},
		{"name": "双鸭山市", "value": 24.2},
		{"name": "大庆市", "value": 21.1},
		{"name": "伊春市", "value": 27.4},
		{"name": "佳木斯市", "value": 23.3},
		{"name": "七台河市", "value": 22.5},
		{"name": "黑河市", "value": 23.1},
		{"name": "绥化市", "value": 23.7},
		{"name": "牡丹江市", "value": 25.3},
		{"name": "大兴安岭地区", "value": 23.4}
	],
	"江苏省": [
		{"name": "南京市", "value": 19},
		{"name": "无锡市", "value": 19.8},
		{"name": "徐州市", "value": 19.5},
		{"name": "常州市", "value": 20},
		{"name": "苏州市", "value": 17},
		{"name": "扬州市", "value": 26},
		{"name": "南通市", "value": 30},
		{"name": "连云港市", "value": 20.4},
		{"name": "淮安市", "value": 22.8},
		{"name": "盐城市", "value": 27.3},
		{"name": "镇江市", "value": 23.6},
		{"name": "泰州市", "value": 28.3},
		{"name": "宿迁市", "value": 18.6}
	],
	"浙江省": [
		{"name": "杭州市", "value": 16.9},
		{"name": "宁波市", "value": 18.1},
		{"name": "温州市", "value": 16.5},
		{"name": "嘉兴市", "value": 19.3},
		{"name": "湖州市", "value": 21.3},
		{"name": "绍兴市", "value": 22.6},
		{"name": "金华市", "value": 16},
		{"name": "衢州市", "value": 25.4},
		{"name": "舟山市", "value": 24.9},
		{"name": "丽水市", "value": 21.2},
		{"name": "台州市", "value": 19.6},
		{"name": "黄山市", "value": 24.1}
	],
	"安徽省": [
		{"name": "合肥市", "value": 15.3},
		{"name": "芜湖市", "value": 20.3},
		{"name": "蚌埠市", "value": 18},
		{"name": "淮南市", "value": 21},
		{"name": "马鞍山市", "value": 21.7},
		{"name": "淮北市", "value": 16.5},
		{"name": "铜陵市", "value": 22.7},
		{"name": "安庆市", "value": 21.5},
		{"name": "滁州市", "value": 19.9},
		{"name": "阜阳市", "value": 16.9},
		{"name": "宿州市", "value": 18.2},
		{"name": "六安市", "value": 21.3},
		{"name": "亳州市", "value": 16.5},
		{"name": "池州市", "value": 22},
		{"name": "宣城市", "value": 22.6}
	],
	"福建省": [
		{"name": "福州市", "value": 16.8},
		{"name": "厦门市", "value": 9.6},
		{"name": "莆田市", "value": 18},
		{"name": "三明市", "value": 19.2},
		{"name": "泉州市", "value": 13.2},
		{"name": "漳州市", "value": 17.9},
		{"name": "南平市", "value": 20.9},
		{"name": "龙岩市", "value": 18.2},
		{"name": "宁德市", "value": 18.4}
	],
	"江西省": [
		{"name": "南昌市", "value": 15},
		{"name": "景德镇市", "value": 16.6},
		{"name": "萍乡市", "value": 19.4},
		{"name": "九江市", "value": 17.7},
		{"name": "新余市", "value": 17.7},
		{"name": "鹰潭市", "value": 17.5},
		{"name": "抚州市", "value": 16.4},
		{"name": "赣州市", "value": 15.6},
		{"name": "吉安市", "value": 17.8},
		{"name": "宜春市", "value": 18},
		{"name": "上饶市", "value": 17.7}
	],
	"山东省": [
		{"name": "济南市", "value": 20},
		{"name": "青岛市", "value": 20.3},
		{"name": "淄博市", "value": 23.2},
		{"name": "枣庄市", "value": 18.6},
		{"name": "东营市", "value": 20.4},
		{"name": "威海市", "value": 27.3},
		{"name": "烟台市", "value": 25.7},
		{"name": "潍坊市", "value": 21.8},
		{"name": "济宁市", "value": 19.5},
		{"name": "泰安市", "value": 22.1},
		{"name": "日照市", "value": 22.4},
		{"name": "临沂市", "value": 19.6},
		{"name": "德州市", "value": 20.7},
		{"name": "聊城市", "value": 19},
		{"name": "滨州市", "value": 21.8},
		{"name": "菏泽市", "value": 18.3}
	],
	"河南省": [
		{"name": "郑州市", "value": 12.8},
		{"name": "开封市", "value": 19.3},
		{"name": "洛阳市", "value": 18.3},
		{"name": "平顶山市", "value": 18.3},
		{"name": "安阳市", "value": 18.3},
		{"name": "鹤壁市", "value": 16.4},
		{"name": "新乡市", "value": 17.7},
		{"name": "焦作市", "value": 18.9},
		{"name": "濮阳市", "value": 17.7},
		{"name": "济源市", "value": 18.7},
		{"name": "漯河市", "value": 21},
		{"name": "三门峡市", "value": 19.8},
		{"name": "南阳市", "value": 18.9},
		{"name": "商丘市", "value": 18.1},
		{"name": "信阳市", "value": 19.3},
		{"name": "周口市", "value": 19.8},
		{"name": "许昌市", "value": 19.7},
		{"name": "驻马店市", "value": 19.8}
	],
	"湖北省": [
		{"name": "武汉市", "value": 17.2},
		{"name": "黄石市", "value": 17},
		{"name": "十堰市", "value": 19},
		{"name": "宜昌市", "value": 25},
		{"name": "襄阳市", "value": 20.7},
		{"name": "鄂州市", "value": 18.5},
		{"name": "荆州市", "value": 23.7},
		{"name": "荆门市", "value": 22.8},
		{"name": "孝感市", "value": 20.8},
		{"name": "黄冈市", "value": 21.4},
		{"name": "咸宁市", "value": 17.7},
		{"name": "随州市", "value": 20.9},
		{"name": "恩施土家族苗族自治州", "value": 20.6},
		{"name": "潜江市", "value": 22.7},
		{"name": "天门市", "value": 25.8},
		{"name": "仙桃市", "value": 22.9},
		{"name": "神农架林区", "value": 21.8}
	],
	"湖南省": [
		{"name": "长沙市", "value": 15.3},
		{"name": "株洲市", "value": 19.9},
		{"name": "湘潭市", "value": 21.9},
		{"name": "衡阳市", "value": 20.2},
		{"name": "邵阳市", "value": 20.8},
		{"name": "岳阳市", "value": 20.3},
		{"name": "常德市", "value": 25},
		{"name": "张家界市", "value": 21.8},
		{"name": "益阳市", "value": 22.7},
		{"name": "永州市", "value": 19.6},
		{"name": "怀化市", "value": 21.1},
		{"name": "郴州市", "value": 17.7},
		{"name": "娄底市", "value": 19.3},
		{"name": "湘西土家族苗族自治州", "value": 19}
	],
	"广东省": [
		{"name": "广州市", "value": 11.4},
		{"name": "韶关市", "value": 18.4},
		{"name": "深圳市", "value": 5.4},
		{"name": "珠海市", "value": 10},
		{"name": "汕头市", "value": 15.5},
		{"name": "佛山市", "value": 10.5},
		{"name": "江门市", "value": 18.3},
		{"name": "湛江市", "value": 16.8},
		{"name": "茂名市", "value": 16.8},
		{"name": "肇庆市", "value": 16.4},
		{"name": "惠州市", "value": 10.1},
		{"name": "梅州市", "value": 20},
		{"name": "汕尾市", "value": 14.9},
		{"name": "河源市", "value": 16.5},
		{"name": "阳江市", "value": 17},
		{"name": "清远市", "value": 16.3},
		{"name": "东莞市", "value": 5.5},
		{"name": "潮州市", "value": 19.2},
		{"name": "揭阳市", "value": 16.1},
		{"name": "云浮市", "value": 17.4},
		{"name": "中山市", "value": 8.9}
	],
	"广西壮族自治区": [
		{"name": "南宁市", "value": 14.8},
		{"name": "柳州市", "value": 17.2},
		{"name": "桂林市", "value": 20.3},
		{"name": "梧州市", "value": 16.7},
		{"name": "北海市", "value": 16.1},
		{"name": "防城港市", "value": 14.1},
		{"name": "钦州市", "value": 15.8},
		{"name": "贵港市", "value": 16.4},
		{"name": "玉林市", "value": 15.8},
		{"name": "百色市", "value": 16.9},
		{"name": "贺州市", "value": 17},
		{"name": "河池市", "value": 17.8},
		{"name": "来宾市", "value": 17.8},
		{"name": "崇左市", "value": 18}
	],
	"海南省": [
		{"name": "海口市", "value": 14.7},
		{"name": "三亚市", "value": 10.4},
		{"name": "三沙市", "value": 7.4},
		{"name": "儋州市", "value": 13.2},
		{"name": "五指山市", "value": 14.2},
		{"name": "琼海市", "value": 19.2},
		{"name": "文昌市", "value": 22.1},
		{"name": "万宁市", "value": 18.1},
		{"name": "东方市", "value": 13.6},
		{"name": "定安县", "value": 19.6},
		{"name": "屯昌县", "value": 17.3},
		{"name": "澄迈县", "value": 17.4},
		{"name": "临高县", "value": 16.5},
		{"name": "白沙黎族自治县", "value": 13.8},
		{"name": "昌江黎族自治县", "value": 14.1},
		{"name": "乐东黎族自治县", "value": 14.8},
		{"name": "陵水黎族自治县", "value": 14.9},
		{"name": "保亭黎族苗族自治县", "value": 14.8},
		{"name": "琼中黎族苗族自治县", "value": 15.2}
	],
	"四川省": [
		{"name": "成都市", "value": 18},
		{"name": "自贡市", "value": 27.3},
		{"name": "攀枝花市", "value": 19.8},
		{"name": "泸州市", "value": 23},
		{"name": "德阳市", "value": 25.8},
		{"name": "绵阳市", "value": 23.7},
		{"name": "广元市", "value": 24.5},
		{"name": "遂宁市", "value": 25.2},
		{"name": "乐山市", "value": 24.5},
		{"name": "南充市", "value": 26},
		{"name": "眉山市", "value": 24.7},
		{"name": "宜宾市", "value": 20.6},
		{"name": "广安市", "value": 24.8},
		{"name": "达州市", "value": 22.4},
		{"name": "雅安市", "value": 21.5},
		{"name": "内江市", "value": 25.2},
		{"name": "巴中市", "value": 24.5},
		{"name": "资阳市", "value": 28.3},
		{"name": "阿坝藏族羌族自治州", "value": 14.3},
		{"name": "甘孜藏族自治州", "value": 11.4},
		{"name": "凉山彝族自治州", "value": 12.4}
	],
	"贵州省": [
		{"name": "贵阳市", "value": 13.3},
		{"name": "六盘水市", "value": 13.5},
		{"name": "遵义市", "value": 17.1},
		{"name": "安顺市", "value": 15.9},
		{"name": "毕节市", "value": 13.8},
		{"name": "铜仁市", "value": 17.6},
		{"name": "黔西南布依族苗族自治州", "value": 14.7},
		{"name": "黔东南苗族侗族自治州", "value": 17.1},
		{"name": "黔南布依族苗族自治州", "value": 16.8}
	],
	"云南省": [
		{"name": "昆明市", "value": 14.4},
		{"name": "曲靖市", "value": 14.9},
		{"name": "玉溪市", "value": 16.6},
		{"name": "保山市", "value": 17.8},
		{"name": "昭通市", "value": 12.7},
		{"name": "丽江市", "value": 14.5},
		{"name": "普洱市", "value": 15.8},
		{"name": "临沧市", "value": 15.0},
		{"name": "楚雄彝族自治州", "value": 17.6},
		{"name": "红河哈尼族彝族自治州", "value": 14.9},
		{"name": "文山壮族苗族自治州", "value": 13.9},
		{"name": "西双版纳傣族自治州", "value": 12.8},
		{"name": "大理白族自治州", "value": 17},
		{"name": "德宏傣族景颇族自治州", "value": 13.2},
		{"name": "怒江傈僳族自治州", "value": 12.1},
		{"name": "迪庆藏族自治州", "value": 12.7}
	],
	"西藏自治区": [
		{"name": "拉萨市", "value": 8.5},
		{"name": "日喀则市"},
		{"name": "阿里地区", "value": 6.8},
		{"name": "昌都市", "value": 8.5},
		{"name": "林芝市", "value": 7.9},
		{"name": "山南市", "value": 11.4},
		{"name": "那曲市", "value": 6.7}
	],
	"陕西省": [
		{"name": "西安市", "value": 16},
		{"name": "铜川市", "value": 21.6},
		{"name": "宝鸡市", "value": 22.7},
		{"name": "咸阳市", "value": 21.5},
		{"name": "渭南市", "value": 22.9},
		{"name": "延安市", "value": 15.6},
		{"name": "汉中市", "value": 24.3},
		{"name": "商洛市", "value": 19.5},
		{"name": "榆林市", "value": 16.4},
		{"name": "安康市", "value": 21}
	],
	"甘肃省": [
		{"name": "兰州市", "value": 16.6},
		{"name": "嘉峪关市", "value": 15.2},
		{"name": "金昌市", "value": 18.2},
		{"name": "白银市", "value": 19},
		{"name": "天水市", "value": 17},
		{"name": "武威市", "value": 18.6},
		{"name": "张掖市", "value": 17.9},
		{"name": "平凉市", "value": 19},
		{"name": "酒泉市", "value": 16.8},
		{"name": "定西市", "value": 17.9},
		{"name": "陇南市", "value": 16.4},
		{"name": "庆阳市", "value": 18},
		{"name": "甘南藏族自治州", "value": 12.5},
		{"name": "临夏回族自治州", "value": 13.6}
	],
	"青海省": [
		{"name": "西宁市", "value": 14.4},
		{"name": "海东市", "value": 14.2},
		{"name": "海北藏族自治州", "value": 10.5},
		{"name": "黄南藏族自治州", "value": 8.3},
		{"name": "海南藏族自治州", "value": 9.6},
		{"name": "果洛藏族自治州", "value": 6.4},
		{"name": "玉树藏族自治州", "value": 7.5},
		{"name": "海西蒙古族藏族自治州", "value": 7.1}
	],
	"宁夏回族自治区": [
		{"name": "银川市", "value": 12.8},
		{"name": "石嘴山市", "value": 16.9},
		{"name": "吴忠市", "value": 12.8},
		{"name": "固原市", "value": 13.8},
		{"name": "中卫市", "value": 13.7}
	],
	"新疆维吾尔自治区": [
		{"name": "乌鲁木齐市", "value": 13.3},
		{"name": "克拉玛依市", "value": 14},
		{"name": "吐鲁番市", "value": 10.4},
		{"name": "哈密市", "value": 14.7},
		{"name": "昌吉回族自治州", "value": 15.6},
		{"name": "博尔塔拉蒙古自治州", "value": 13.8},
		{"name": "巴音郭楞蒙古自治州", "value": 11.9},
		{"name": "伊犁哈萨克自治州", "value": 12.0},
		{"name": "克孜勒苏柯尔克孜自治州", "value": 8.8},
		{"name": "阿克苏地区", "value": 9.5},
		{"name": "喀什地区", "value": 8.5},
		{"name": "和田地区", "value": 7.3},
		{"name": "塔城地区", "value": 15.2},
		{"name": "阿勒泰地区", "value": 11.8},
		{"name": "北屯市", "value": 12.8},
		{"name": "五家渠市", "value": 12.8},
		{"name": "石河子市", "value": 12.8},
		{"name": "胡杨河市", "value": 12.8},
		{"name": "双河市", "value": 12.8},
		{"name": "阿拉尔市", "value": 12.8},
		{"name": "图木舒克市", "value": 12.8},
		{"name": "铁门关市", "value": 12.8},
		{"name": "可克达拉市", "value": 12.8},
		{"name": "昆玉市", "value": 12.8}
	]
}